name: voila
channels:
    - conda-forge
dependencies:
    - python==3.9.13
    - ipython==8.12.0
    - pandas==1.5.1
    - plotly==5.11.0
    - openpyxl==3.0.10
    - ipywidgets==7.7.2
    - voila==0.3.7